# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvis2Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jarvis2Ui(object):
    def setupUi(self, jarvis2Ui):
        jarvis2Ui.setObjectName("jarvis2Ui")
        jarvis2Ui.resize(1491, 794)
        self.centralwidget = QtWidgets.QWidget(jarvis2Ui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1491, 791))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/OMEN/Downloads/ezgif.com-gif-maker (3).gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1120, 520, 371, 191))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/OMEN/Downloads/jarvis-iron-man.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 700, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(209, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 700, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(209, 0, 0);\n"
"background-color: rgb(154, 154, 154);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 361, 121))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:14px ;\n")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(370, 10, 361, 121))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:14px ;\n")
        self.textBrowser_2.setObjectName("textBrowser_2")
        jarvis2Ui.setCentralWidget(self.centralwidget)

        self.retranslateUi(jarvis2Ui)
        QtCore.QMetaObject.connectSlotsByName(jarvis2Ui)

    def retranslateUi(self, jarvis2Ui):
        _translate = QtCore.QCoreApplication.translate
        jarvis2Ui.setWindowTitle(_translate("jarvis2Ui", "MainWindow"))
        self.pushButton.setText(_translate("jarvis2Ui", "Run"))
        self.pushButton_2.setText(_translate("jarvis2Ui", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jarvis2Ui = QtWidgets.QMainWindow()
    ui = Ui_jarvis2Ui()
    ui.setupUi(jarvis2Ui)
    jarvis2Ui.show()
    sys.exit(app.exec_())
